#############################
## Sass Lint Configuration ##
#############################

options:
  formatter: stylish
files:
  include: "**/*.s+(a|c)ss"
  ignore:
    - node_modules/**
syntax:
  include:
    - scss
    - sass
rules:
  quotes:
    - 1
    - style: double # single
